"""add roles table

Revision ID: 5fa19e4a8fd0
Revises: 271da6bba801
Create Date: 2025-12-23 17:42:16.258873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.users.enums import RoleEnum
from src.users.models import Role

# revision identifiers, used by Alembic.
revision: str = '5fa19e4a8fd0'
down_revision: Union[str, Sequence[str], None] = '271da6bba801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###

    op.bulk_insert(
        Role.__table__,
        [
            {"id": 1, "name": RoleEnum.ADMIN.value},
            {"id": 2, "name": RoleEnum.MODERATOR.value},
            {"id": 3, "name": RoleEnum.USER.value},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
